### ISSUE TITLE
Consider using @:op(+) instead of @:op(&)

### ISSUE THREAD

**Issue by kevinresol** [haxetink/tink_chunk#2]
Well, it is mostly personal preference, but it can also be argued by the fact that the Haxe language itself uses `+` to denote concatenation on Strings.

**Comment by back2dos** [comment]
The result would be ambiguity that can silently sneak in string concatenation where it should not be. Consider this:

```haxe
chunk1 & string1 & string2; //compiles, because `&` is left associative
string1 & string2 & chunk1; //does not compile because `String` & `String` is not defined

//if we used `+` for chunk concatenation, this would work:

string1 + string2 + chunk1; // but it would mean `chunkConcat(stringConcat(string1, string2), chunk2)`
```

On some platforms string concatenation is pretty slow, because the memory actually gets copied around (e.g. Java, C++, neko), unlike on e.g. the V8 where they use more sophisticated string implementations.

There's that and also the fact that I think defining `+` to mean something non-commutative is a bad idea. But let's not complain about things that'll never change anyway.

I really hope we get operator overloading through static extensions, then everyone can choose his own method of shooting himself in the foot :D

**Comment by kevinresol** [comment]
okay, that make sense. but the result of the limitation really hurts my eyes. 😢
